CREATE FULLTEXT CATALOG [ProdutosFTS] WITH ACCENT_SENSITIVITY = OFF

CREATE FULLTEXT INDEX ON TB_Produto_Master_Data
(NM_PRODUTO_COMPLETO, TX_MARCA_PRODUTO)
KEY INDEX PK_ProdutoMasterData
ON [ProdutosFTS]
WITH STOPLIST = SYSTEM